name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Release APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease

      - name: Move APK File
        run: |
          RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -z "$RELEASE_APK" ]; then
            echo "Error: APK file not found!"
            exit 1
          fi
          mv "$RELEASE_APK" "LittleGooseOffice_${GITHUB_REF_NAME}.apk"

      - name: Upload Release Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ secrets.GINTOKEN }}
          generateReleaseNotes: true
